name: Robot Framework GUI Automated Tests Pipeline

on: push

jobs:
  robot-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests  # Se for usar API
          pip install robotframework-yaml      # Se for usar arquivos YAML

      - name: Run Robot Tests
        run: |
          robot --outputdir results tests/functional_tests/home.robot

      - name: Upload Robot Reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: results
          if-no-files-found: ignore

      - name: Upload Robot Logs
        uses: actions/upload-artifact@v4
        with:
          name: robot-logs
          path: results/log.html
          if-no-files-found: ignore
