name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary
          pip install -r requirements.txt

      - name: Setup Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip || true
          unzip /tmp/chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Run Robot Framework Tests
        run: |
          robot -d results tests/home.robot
          robot -d results tests/features

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results
